#!/usr/bin/env python
import os
from ast import literal_eval
import subprocess
import logging
import parser
from typing import Dict, List

logger = logging.getLogger(__name__)

BLOCK_SIZE = 4096 * 1024  # 4MB blocks
DVD_SECTOR_SIZE = 2048


def lsdvd(video_ts):
    res = subprocess.run(["lsdvd", "-x", "-Oy", video_ts], stdout=subprocess.PIPE, encoding="utf-8")
    try:
        data = literal_eval(res.stdout.split("lsdvd = ", 1)[-1])
    except:
        data = {}
        print(res.stdout)
    return data


def find_vob(video_ts: str) -> Dict[int, List[Dict]]:
    results = {}
    for fn in sorted(os.listdir(video_ts)):
        fnu = fn.upper()
        name, ext = fnu.split(".", 1)
        if ext != "VOB":
            continue

        spl = name.split("_")

        if spl[0] == "VTS":
            title_set_id = int(spl[1])
            object_id = int(spl[2])

            # Video Object 0 is the menu for this Title
            if object_id == 0:
                continue

            if not title_set_id in results:
                results[title_set_id] = []

            results[title_set_id].append(
                {
                    "title_set": title_set_id,
                    "object": object_id,
                    "file": os.path.join(video_ts, fn),
                }
            )

    logger.debug(f"Located VOBs: {results}")

    return results


def merge_vobs(video_ts: str, output: str) -> Dict[int, str]:
    res = {}

    for title_set, objects in find_vob(video_ts).items():
        output_fn = os.path.join(output, f"ts_{title_set:02n}.vob")
        logger.info(f"Merging {len(objects)} object(s) of title set {title_set} into '{output_fn}'…")

        res[title_set] = output_fn

        with open(output_fn, "wb") as outfh:
            for obj in sorted(objects, key=lambda o: o["object"]):
                logger.debug(f"Reading title {title_set} object {obj['object']}: {obj['file']}…")

                with open(obj["file"], "rb") as infh:
                    while True:
                        data = infh.read(BLOCK_SIZE)
                        if not data:
                            break

                        outfh.write(data)
    return res


def split_tracks(video_ts, merged, output):
    {
        "ix": 1,
        "length": 5634.84,
        "vts_id": "DVDVIDEO-VTS",
        "vts": 1,
        "ttn": 1,
        "fps": 25.0,
        "format": "PAL",
        "aspect": "4/3",
        "width": 720,
        "height": 576,
        "df": "?",
        "palette": [
            "286df0",
            "51f05a",
            "108080",
            "ea8080",
            "39c273",
            "3bc473",
            "4fdd70",
            "108080",
            "108080",
            "108080",
            "108080",
            "108080",
            "ea8080",
            "ea8080",
            "ea8080",
            "d9807f",
        ],
        "angles": 1,
        "audio": [
            {
                "ix": 1,
                "langcode": "en",
                "language": "English",
                "format": "ac3",
                "frequency": 48000,
                "quantization": "drc",
                "channels": 2,
                "ap_mode": 0,
                "content": "Undefined",
                "streamid": "0x80",
            },
            {
                "ix": 2,
                "langcode": "no",
                "language": "Norsk",
                "format": "ac3",
                "frequency": 48000,
                "quantization": "drc",
                "channels": 2,
                "ap_mode": 0,
                "content": "Undefined",
                "streamid": "0x81",
            },
            {
                "ix": 3,
                "langcode": "da",
                "language": "Dansk",
                "format": "ac3",
                "frequency": 48000,
                "quantization": "drc",
                "channels": 2,
                "ap_mode": 0,
                "content": "Undefined",
                "streamid": "0x82",
            },
        ],
        "chapter": [
            {"ix": 1, "length": 1632.24, "startcell": 1},
            {"ix": 2, "length": 492.8, "startcell": 3},
            {"ix": 3, "length": 587.92, "startcell": 4},
            {"ix": 4, "length": 449.04, "startcell": 5},
            {"ix": 5, "length": 513.76, "startcell": 6},
            {"ix": 6, "length": 432.72, "startcell": 7},
            {"ix": 7, "length": 1525.88, "startcell": 8},
            {"ix": 8, "length": 0.48, "startcell": 9},
        ],
        "cell": [
            {"ix": 1, "length": 2.0, "first_sector": 0, "last_sector": 576},
            {"ix": 2, "length": 1630.24, "first_sector": 577, "last_sector": 485674},
            {"ix": 3, "length": 492.8, "first_sector": 485675, "last_sector": 642544},
            {"ix": 4, "length": 587.92, "first_sector": 642545, "last_sector": 831433},
            {"ix": 5, "length": 449.04, "first_sector": 831434, "last_sector": 978897},
            {"ix": 6, "length": 513.76, "first_sector": 978898, "last_sector": 1153925},
            {"ix": 7, "length": 432.72, "first_sector": 1153926, "last_sector": 1294311},
            {"ix": 8, "length": 1525.88, "first_sector": 1294312, "last_sector": 1735081},
            {"ix": 9, "length": 0.48, "first_sector": 1735082, "last_sector": 1735260},
        ],
        "subp": [
            {"ix": 1, "langcode": "en", "language": "English", "content": "Normal", "streamid": "0x20"},
            {"ix": 2, "langcode": "no", "language": "Norsk", "content": "Normal", "streamid": "0x21"},
            {"ix": 3, "langcode": "da", "language": "Dansk", "content": "Normal", "streamid": "0x22"},
            {"ix": 4, "langcode": "no", "language": "Norsk", "content": "Forced", "streamid": "0x23"},
            {"ix": 5, "langcode": "da", "language": "Dansk", "content": "Forced", "streamid": "0x24"},
        ],
    }
    {
        "ix": 2,
        "length": 0.48,
        "vts_id": "DVDVIDEO-VTS",
        "vts": 1,
        "ttn": 2,
        "fps": 25.0,
        "format": "PAL",
        "aspect": "4/3",
        "width": 720,
        "height": 576,
        "df": "?",
        "palette": [
            "286df0",
            "51f05a",
            "108080",
            "ea8080",
            "902235",
            "6addca",
            "d29210",
            "5b4992",
            "7b8080",
            "d18080",
            "30b66d",
            "4f515b",
            "1c77b6",
            "61cfcf",
            "88b33a",
            "3caea4",
        ],
        "angles": 1,
        "audio": [
            {
                "ix": 1,
                "langcode": "en",
                "language": "English",
                "format": "ac3",
                "frequency": 48000,
                "quantization": "drc",
                "channels": 2,
                "ap_mode": 0,
                "content": "Undefined",
                "streamid": "0x80",
            },
            {
                "ix": 2,
                "langcode": "no",
                "language": "Norsk",
                "format": "ac3",
                "frequency": 48000,
                "quantization": "drc",
                "channels": 2,
                "ap_mode": 0,
                "content": "Undefined",
                "streamid": "0x81",
            },
            {
                "ix": 3,
                "langcode": "da",
                "language": "Dansk",
                "format": "ac3",
                "frequency": 48000,
                "quantization": "drc",
                "channels": 2,
                "ap_mode": 0,
                "content": "Undefined",
                "streamid": "0x82",
            },
        ],
        "chapter": [{"ix": 1, "length": 0.48, "startcell": 1}],
        "cell": [{"ix": 1, "length": 0.48, "first_sector": 1735261, "last_sector": 1735439}],
        "subp": [
            {"ix": 1, "langcode": "en", "language": "English", "content": "Normal", "streamid": "0x20"},
            {"ix": 2, "langcode": "no", "language": "Norsk", "content": "Normal", "streamid": "0x21"},
            {"ix": 3, "langcode": "da", "language": "Dansk", "content": "Normal", "streamid": "0x22"},
            {"ix": 4, "langcode": "no", "language": "Norsk", "content": "Forced", "streamid": "0x23"},
            {"ix": 5, "langcode": "da", "language": "Dansk", "content": "Forced", "streamid": "0x24"},
        ],
    }
    {
        "ix": 3,
        "length": 9.52,
        "vts_id": "DVDVIDEO-VTS",
        "vts": 2,
        "ttn": 1,
        "fps": 25.0,
        "format": "PAL",
        "aspect": "4/3",
        "width": 720,
        "height": 576,
        "df": "?",
        "palette": [
            "286df0",
            "51f05a",
            "108080",
            "ea8080",
            "39c273",
            "3bc473",
            "4fdd70",
            "108080",
            "108080",
            "108080",
            "108080",
            "108080",
            "ea8080",
            "ea8080",
            "ea8080",
            "d9807f",
        ],
        "angles": 1,
        "audio": [
            {
                "ix": 1,
                "langcode": "xx",
                "language": "Unknown",
                "format": "ac3",
                "frequency": 48000,
                "quantization": "drc",
                "channels": 6,
                "ap_mode": 0,
                "content": "Undefined",
                "streamid": "0x80",
            }
        ],
        "chapter": [{"ix": 1, "length": 9.04, "startcell": 1}, {"ix": 2, "length": 0.48, "startcell": 2}],
        "cell": [{"ix": 1, "length": 9.04, "first_sector": 0, "last_sector": 2788}, {"ix": 2, "length": 0.48, "first_sector": 2789, "last_sector": 2967}],
        "subp": [],
    }

    lsd = lsdvd(video_ts)

    res = {}
    for track in lsd["track"]:
        print(track)
        title_set: int = track["vts"]
        track_id = track["ix"]
        logger.debug(f"Title {title_set} track {track_id}")

        output_fn = os.path.join(output, f"ts_{title_set:02n}_ch_{track_id:02n}.vob")

        with open(merged[title_set], "rb") as infh, open(output_fn, "wb") as outfh:
            for cell in track["cell"]:
                start = cell["first_sector"] * DVD_SECTOR_SIZE
                end = cell["last_sector"] * DVD_SECTOR_SIZE
                length = end - start

                infh.seek(start)

                logging.debug(f"Track {track_id}, cell {cell['ix']}: copying {length} bytes from {merged[title_set]}:{start}-{end}")
                transfer(infh, outfh, length)

        res[track_id] = output_fn

    return res


def transfer(infh, outfh, num):
    while num:
        b = min(BLOCK_SIZE, num)
        data = infh.read(b)
        outfh.write(data)
        num -= len(data)


def chapters2cells(chapters: List[Dict], cells: List[Dict]):
    _cells = {}
    for cell in cells:
        _cells[cell["ix"]] = cell

    _chapters = {}
    for _chapter in chapters:
        chapter = _chapter.copy()
        _chapters[chapter.pop("ix")] = chapter

    res = {}

    for ix, chapter in _chapters.items():
        x = []
        i = chapter["startcell"]
        while sum([y["length"] for y in x]) < chapter["length"]:
            x.append(_cells[i])
            i += 1
        res[ix] = x

    return res


x = {
    "device": "output/Countdown To Christmas/VIDEO_TS",
    "title": "unknown",
    "vmg_id": "DVDVIDEO-VMG",
    "provider_id": "",
    "track": [
        {
            "ix": 1,
            "length": 5634.84,
            "vts_id": "DVDVIDEO-VTS",
            "vts": 1,
            "ttn": 1,
            "fps": 25.0,
            "format": "PAL",
            "aspect": "4/3",
            "width": 720,
            "height": 576,
            "df": "?",
            "palette": [
                "286df0",
                "51f05a",
                "108080",
                "ea8080",
                "39c273",
                "3bc473",
                "4fdd70",
                "108080",
                "108080",
                "108080",
                "108080",
                "108080",
                "ea8080",
                "ea8080",
                "ea8080",
                "d9807f",
            ],
            "angles": 1,
            "audio": [
                {
                    "ix": 1,
                    "langcode": "en",
                    "language": "English",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x80",
                },
                {
                    "ix": 2,
                    "langcode": "no",
                    "language": "Norsk",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x81",
                },
                {
                    "ix": 3,
                    "langcode": "da",
                    "language": "Dansk",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x82",
                },
            ],
            "chapter": [
                {"ix": 1, "length": 1632.24, "startcell": 1},
                {"ix": 2, "length": 492.8, "startcell": 3},
                {"ix": 3, "length": 587.92, "startcell": 4},
                {"ix": 4, "length": 449.04, "startcell": 5},
                {"ix": 5, "length": 513.76, "startcell": 6},
                {"ix": 6, "length": 432.72, "startcell": 7},
                {"ix": 7, "length": 1525.88, "startcell": 8},
                {"ix": 8, "length": 0.48, "startcell": 9},
            ],
            "cell": [
                {"ix": 1, "length": 2.0, "first_sector": 0, "last_sector": 576},
                {"ix": 2, "length": 1630.24, "first_sector": 577, "last_sector": 485674},
                {"ix": 3, "length": 492.8, "first_sector": 485675, "last_sector": 642544},
                {"ix": 4, "length": 587.92, "first_sector": 642545, "last_sector": 831433},
                {"ix": 5, "length": 449.04, "first_sector": 831434, "last_sector": 978897},
                {"ix": 6, "length": 513.76, "first_sector": 978898, "last_sector": 1153925},
                {"ix": 7, "length": 432.72, "first_sector": 1153926, "last_sector": 1294311},
                {"ix": 8, "length": 1525.88, "first_sector": 1294312, "last_sector": 1735081},
                {"ix": 9, "length": 0.48, "first_sector": 1735082, "last_sector": 1735260},
            ],
            "subp": [
                {"ix": 1, "langcode": "en", "language": "English", "content": "Normal", "streamid": "0x20"},
                {"ix": 2, "langcode": "no", "language": "Norsk", "content": "Normal", "streamid": "0x21"},
                {"ix": 3, "langcode": "da", "language": "Dansk", "content": "Normal", "streamid": "0x22"},
                {"ix": 4, "langcode": "no", "language": "Norsk", "content": "Forced", "streamid": "0x23"},
                {"ix": 5, "langcode": "da", "language": "Dansk", "content": "Forced", "streamid": "0x24"},
            ],
        },
        {
            "ix": 2,
            "length": 0.48,
            "vts_id": "DVDVIDEO-VTS",
            "vts": 1,
            "ttn": 2,
            "fps": 25.0,
            "format": "PAL",
            "aspect": "4/3",
            "width": 720,
            "height": 576,
            "df": "?",
            "palette": [
                "286df0",
                "51f05a",
                "108080",
                "ea8080",
                "902235",
                "6addca",
                "d29210",
                "5b4992",
                "7b8080",
                "d18080",
                "30b66d",
                "4f515b",
                "1c77b6",
                "61cfcf",
                "88b33a",
                "3caea4",
            ],
            "angles": 1,
            "audio": [
                {
                    "ix": 1,
                    "langcode": "en",
                    "language": "English",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x80",
                },
                {
                    "ix": 2,
                    "langcode": "no",
                    "language": "Norsk",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x81",
                },
                {
                    "ix": 3,
                    "langcode": "da",
                    "language": "Dansk",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x82",
                },
            ],
            "chapter": [{"ix": 1, "length": 0.48, "startcell": 1}],
            "cell": [{"ix": 1, "length": 0.48, "first_sector": 1735261, "last_sector": 1735439}],
            "subp": [
                {"ix": 1, "langcode": "en", "language": "English", "content": "Normal", "streamid": "0x20"},
                {"ix": 2, "langcode": "no", "language": "Norsk", "content": "Normal", "streamid": "0x21"},
                {"ix": 3, "langcode": "da", "language": "Dansk", "content": "Normal", "streamid": "0x22"},
                {"ix": 4, "langcode": "no", "language": "Norsk", "content": "Forced", "streamid": "0x23"},
                {"ix": 5, "langcode": "da", "language": "Dansk", "content": "Forced", "streamid": "0x24"},
            ],
        },
        {
            "ix": 3,
            "length": 9.52,
            "vts_id": "DVDVIDEO-VTS",
            "vts": 2,
            "ttn": 1,
            "fps": 25.0,
            "format": "PAL",
            "aspect": "4/3",
            "width": 720,
            "height": 576,
            "df": "?",
            "palette": [
                "286df0",
                "51f05a",
                "108080",
                "ea8080",
                "39c273",
                "3bc473",
                "4fdd70",
                "108080",
                "108080",
                "108080",
                "108080",
                "108080",
                "ea8080",
                "ea8080",
                "ea8080",
                "d9807f",
            ],
            "angles": 1,
            "audio": [
                {
                    "ix": 1,
                    "langcode": "xx",
                    "language": "Unknown",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 6,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x80",
                }
            ],
            "chapter": [{"ix": 1, "length": 9.04, "startcell": 1}, {"ix": 2, "length": 0.48, "startcell": 2}],
            "cell": [{"ix": 1, "length": 9.04, "first_sector": 0, "last_sector": 2788}, {"ix": 2, "length": 0.48, "first_sector": 2789, "last_sector": 2967}],
            "subp": [],
        },
        {
            "ix": 4,
            "length": 183.6,
            "vts_id": "DVDVIDEO-VTS",
            "vts": 3,
            "ttn": 1,
            "fps": 25.0,
            "format": "PAL",
            "aspect": "4/3",
            "width": 720,
            "height": 576,
            "df": "?",
            "palette": [
                "286df0",
                "51f05a",
                "108080",
                "ea8080",
                "39c273",
                "3bc473",
                "4fdd70",
                "108080",
                "108080",
                "108080",
                "108080",
                "108080",
                "ea8080",
                "ea8080",
                "ea8080",
                "d9807f",
            ],
            "angles": 1,
            "audio": [
                {
                    "ix": 1,
                    "langcode": "en",
                    "language": "English",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x80",
                },
                {
                    "ix": 2,
                    "langcode": "no",
                    "language": "Norsk",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x81",
                },
                {
                    "ix": 3,
                    "langcode": "da",
                    "language": "Dansk",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x82",
                },
            ],
            "chapter": [
                {"ix": 1, "length": 7.8, "startcell": 1},
                {"ix": 2, "length": 114.96, "startcell": 2},
                {"ix": 3, "length": 60.36, "startcell": 4},
                {"ix": 4, "length": 0.48, "startcell": 6},
            ],
            "cell": [
                {"ix": 1, "length": 7.8, "first_sector": 0, "last_sector": 2399},
                {"ix": 2, "length": 3.56, "first_sector": 2400, "last_sector": 3631},
                {"ix": 3, "length": 111.4, "first_sector": 3632, "last_sector": 58961},
                {"ix": 4, "length": 3.56, "first_sector": 58962, "last_sector": 60252},
                {"ix": 5, "length": 56.8, "first_sector": 60253, "last_sector": 88424},
                {"ix": 6, "length": 0.48, "first_sector": 88425, "last_sector": 88603},
            ],
            "subp": [],
        },
        {
            "ix": 5,
            "length": 111.88,
            "vts_id": "DVDVIDEO-VTS",
            "vts": 3,
            "ttn": 2,
            "fps": 25.0,
            "format": "PAL",
            "aspect": "4/3",
            "width": 720,
            "height": 576,
            "df": "?",
            "palette": [
                "286df0",
                "51f05a",
                "108080",
                "ea8080",
                "39c273",
                "3bc473",
                "4fdd70",
                "108080",
                "108080",
                "108080",
                "108080",
                "108080",
                "ea8080",
                "ea8080",
                "ea8080",
                "d9807f",
            ],
            "angles": 1,
            "audio": [
                {
                    "ix": 1,
                    "langcode": "en",
                    "language": "English",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x80",
                },
                {
                    "ix": 2,
                    "langcode": "no",
                    "language": "Norsk",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x81",
                },
                {
                    "ix": 3,
                    "langcode": "da",
                    "language": "Dansk",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x82",
                },
            ],
            "chapter": [{"ix": 1, "length": 111.4, "startcell": 1}, {"ix": 2, "length": 0.48, "startcell": 2}],
            "cell": [
                {"ix": 1, "length": 111.4, "first_sector": 3632, "last_sector": 58961},
                {"ix": 2, "length": 0.48, "first_sector": 88425, "last_sector": 88603},
            ],
            "subp": [],
        },
        {
            "ix": 6,
            "length": 57.28,
            "vts_id": "DVDVIDEO-VTS",
            "vts": 3,
            "ttn": 3,
            "fps": 25.0,
            "format": "PAL",
            "aspect": "4/3",
            "width": 720,
            "height": 576,
            "df": "?",
            "palette": [
                "286df0",
                "51f05a",
                "108080",
                "ea8080",
                "39c273",
                "3bc473",
                "4fdd70",
                "108080",
                "108080",
                "108080",
                "108080",
                "108080",
                "ea8080",
                "ea8080",
                "ea8080",
                "d9807f",
            ],
            "angles": 1,
            "audio": [
                {
                    "ix": 1,
                    "langcode": "en",
                    "language": "English",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x80",
                },
                {
                    "ix": 2,
                    "langcode": "no",
                    "language": "Norsk",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x81",
                },
                {
                    "ix": 3,
                    "langcode": "da",
                    "language": "Dansk",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x82",
                },
            ],
            "chapter": [{"ix": 1, "length": 56.8, "startcell": 1}, {"ix": 2, "length": 0.48, "startcell": 2}],
            "cell": [
                {"ix": 1, "length": 56.8, "first_sector": 60253, "last_sector": 88424},
                {"ix": 2, "length": 0.48, "first_sector": 88425, "last_sector": 88603},
            ],
            "subp": [],
        },
        {
            "ix": 7,
            "length": 0.48,
            "vts_id": "DVDVIDEO-VTS",
            "vts": 4,
            "ttn": 1,
            "fps": 25.0,
            "format": "PAL",
            "aspect": "16/9",
            "width": 720,
            "height": 576,
            "df": "Pan&Scan",
            "palette": [
                "286df0",
                "51f05a",
                "108080",
                "ea8080",
                "39c273",
                "3bc473",
                "4fdd70",
                "108080",
                "108080",
                "108080",
                "108080",
                "108080",
                "ea8080",
                "ea8080",
                "ea8080",
                "d9807f",
            ],
            "angles": 1,
            "audio": [],
            "chapter": [{"ix": 1, "length": 0.48, "startcell": 1}],
            "cell": [{"ix": 1, "length": 0.48, "first_sector": 0, "last_sector": 50}],
            "subp": [],
        },
        {
            "ix": 8,
            "length": 18.44,
            "vts_id": "DVDVIDEO-VTS",
            "vts": 5,
            "ttn": 1,
            "fps": 25.0,
            "format": "PAL",
            "aspect": "4/3",
            "width": 720,
            "height": 576,
            "df": "?",
            "palette": [
                "286df0",
                "51f05a",
                "108080",
                "ea8080",
                "39c273",
                "3bc473",
                "4fdd70",
                "108080",
                "108080",
                "108080",
                "108080",
                "108080",
                "ea8080",
                "ea8080",
                "ea8080",
                "d9807f",
            ],
            "angles": 1,
            "audio": [
                {
                    "ix": 1,
                    "langcode": "xx",
                    "language": "Unknown",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 6,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x80",
                }
            ],
            "chapter": [{"ix": 1, "length": 17.96, "startcell": 1}, {"ix": 2, "length": 0.48, "startcell": 2}],
            "cell": [{"ix": 1, "length": 17.96, "first_sector": 0, "last_sector": 6594}, {"ix": 2, "length": 0.48, "first_sector": 6595, "last_sector": 6773}],
            "subp": [],
        },
        {
            "ix": 9,
            "length": 0.48,
            "vts_id": "DVDVIDEO-VTS",
            "vts": 6,
            "ttn": 1,
            "fps": 25.0,
            "format": "PAL",
            "aspect": "16/9",
            "width": 720,
            "height": 576,
            "df": "Pan&Scan",
            "palette": [
                "286df0",
                "51f05a",
                "108080",
                "ea8080",
                "39c273",
                "3bc473",
                "4fdd70",
                "108080",
                "108080",
                "108080",
                "108080",
                "108080",
                "ea8080",
                "ea8080",
                "ea8080",
                "d9807f",
            ],
            "angles": 1,
            "audio": [],
            "chapter": [{"ix": 1, "length": 0.48, "startcell": 1}],
            "cell": [{"ix": 1, "length": 0.48, "first_sector": 0, "last_sector": 7}],
            "subp": [],
        },
        {
            "ix": 10,
            "length": 9.0,
            "vts_id": "DVDVIDEO-VTS",
            "vts": 7,
            "ttn": 1,
            "fps": 25.0,
            "format": "PAL",
            "aspect": "16/9",
            "width": 720,
            "height": 576,
            "df": "Pan&Scan",
            "palette": [
                "286df0",
                "51f05a",
                "108080",
                "ea8080",
                "39c273",
                "3bc473",
                "4fdd70",
                "108080",
                "108080",
                "108080",
                "108080",
                "108080",
                "ea8080",
                "ea8080",
                "ea8080",
                "d9807f",
            ],
            "angles": 1,
            "audio": [
                {
                    "ix": 1,
                    "langcode": "xx",
                    "language": "Unknown",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x80",
                }
            ],
            "chapter": [{"ix": 1, "length": 3.0, "startcell": 1}, {"ix": 2, "length": 3.0, "startcell": 2}, {"ix": 3, "length": 3.0, "startcell": 3}],
            "cell": [
                {"ix": 1, "length": 3.0, "first_sector": 0, "last_sector": 70},
                {"ix": 2, "length": 3.0, "first_sector": 71, "last_sector": 143},
                {"ix": 3, "length": 3.0, "first_sector": 144, "last_sector": 215},
            ],
            "subp": [],
        },
        {
            "ix": 11,
            "length": 62.04,
            "vts_id": "DVDVIDEO-VTS",
            "vts": 8,
            "ttn": 1,
            "fps": 25.0,
            "format": "PAL",
            "aspect": "4/3",
            "width": 720,
            "height": 576,
            "df": "?",
            "palette": [
                "286df0",
                "51f05a",
                "108080",
                "ea8080",
                "48d364",
                "ea8080",
                "ea8080",
                "ea8080",
                "ea8080",
                "ea8080",
                "ea8080",
                "ea8080",
                "ea8080",
                "ea8080",
                "ea8080",
                "ea8080",
            ],
            "angles": 1,
            "audio": [
                {
                    "ix": 1,
                    "langcode": "xx",
                    "language": "Unknown",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x80",
                },
                {
                    "ix": 2,
                    "langcode": "xx",
                    "language": "Unknown",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x81",
                },
                {
                    "ix": 3,
                    "langcode": "xx",
                    "language": "Unknown",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x82",
                },
            ],
            "chapter": [{"ix": 1, "length": 62.04, "startcell": 1}],
            "cell": [{"ix": 1, "length": 62.04, "first_sector": 0, "last_sector": 19482}],
            "subp": [{"ix": 1, "langcode": "xx", "language": "Unknown", "content": "Undefined", "streamid": "0x20"}],
        },
        {
            "ix": 12,
            "length": 7.64,
            "vts_id": "DVDVIDEO-VTS",
            "vts": 8,
            "ttn": 2,
            "fps": 25.0,
            "format": "PAL",
            "aspect": "4/3",
            "width": 720,
            "height": 576,
            "df": "?",
            "palette": [
                "286df0",
                "51f05a",
                "108080",
                "ea8080",
                "48d364",
                "ea8080",
                "ea8080",
                "ea8080",
                "ea8080",
                "ea8080",
                "ea8080",
                "ea8080",
                "ea8080",
                "ea8080",
                "ea8080",
                "ea8080",
            ],
            "angles": 1,
            "audio": [
                {
                    "ix": 1,
                    "langcode": "xx",
                    "language": "Unknown",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x80",
                },
                {
                    "ix": 2,
                    "langcode": "xx",
                    "language": "Unknown",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x81",
                },
                {
                    "ix": 3,
                    "langcode": "xx",
                    "language": "Unknown",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x82",
                },
            ],
            "chapter": [{"ix": 1, "length": 7.64, "startcell": 1}],
            "cell": [{"ix": 1, "length": 7.64, "first_sector": 112686, "last_sector": 115105}],
            "subp": [{"ix": 1, "langcode": "xx", "language": "Unknown", "content": "Undefined", "streamid": "0x20"}],
        },
        {
            "ix": 13,
            "length": 0.48,
            "vts_id": "DVDVIDEO-VTS",
            "vts": 9,
            "ttn": 1,
            "fps": 25.0,
            "format": "PAL",
            "aspect": "4/3",
            "width": 720,
            "height": 576,
            "df": "?",
            "palette": [
                "286df0",
                "51f05a",
                "108080",
                "ea8080",
                "902235",
                "6addca",
                "d29210",
                "5b4992",
                "7b8080",
                "d18080",
                "30b66d",
                "4f515b",
                "1c77b6",
                "61cfcf",
                "88b33a",
                "3caea4",
            ],
            "angles": 1,
            "audio": [
                {
                    "ix": 1,
                    "langcode": "en",
                    "language": "English",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x80",
                },
                {
                    "ix": 2,
                    "langcode": "no",
                    "language": "Norsk",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x81",
                },
                {
                    "ix": 3,
                    "langcode": "da",
                    "language": "Dansk",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x82",
                },
            ],
            "chapter": [{"ix": 1, "length": 0.48, "startcell": 1}],
            "cell": [{"ix": 1, "length": 0.48, "first_sector": 0, "last_sector": 178}],
            "subp": [{"ix": 1, "langcode": "xx", "language": "Unknown", "content": "Undefined", "streamid": "0x20"}],
        },
        {
            "ix": 14,
            "length": 19.88,
            "vts_id": "DVDVIDEO-VTS",
            "vts": 9,
            "ttn": 2,
            "fps": 25.0,
            "format": "PAL",
            "aspect": "4/3",
            "width": 720,
            "height": 576,
            "df": "?",
            "palette": [
                "286df0",
                "51f05a",
                "108080",
                "ea8080",
                "902235",
                "6addca",
                "d29210",
                "5b4992",
                "7b8080",
                "d18080",
                "30b66d",
                "4f515b",
                "1c77b6",
                "61cfcf",
                "88b33a",
                "3caea4",
            ],
            "angles": 4,
            "audio": [
                {
                    "ix": 1,
                    "langcode": "en",
                    "language": "English",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x80",
                },
                {
                    "ix": 2,
                    "langcode": "no",
                    "language": "Norsk",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x81",
                },
                {
                    "ix": 3,
                    "langcode": "da",
                    "language": "Dansk",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x82",
                },
            ],
            "chapter": [{"ix": 1, "length": 19.88, "startcell": 1}],
            "cell": [{"ix": 1, "length": 19.88, "first_sector": 179, "last_sector": 9920}],
            "subp": [{"ix": 1, "langcode": "xx", "language": "Unknown", "content": "Undefined", "streamid": "0x20"}],
        },
        {
            "ix": 15,
            "length": 27.04,
            "vts_id": "DVDVIDEO-VTS",
            "vts": 9,
            "ttn": 3,
            "fps": 25.0,
            "format": "PAL",
            "aspect": "4/3",
            "width": 720,
            "height": 576,
            "df": "?",
            "palette": [
                "286df0",
                "51f05a",
                "108080",
                "ea8080",
                "ea8080",
                "48d364",
                "b79227",
                "ea8080",
                "ea8080",
                "ea8080",
                "ea8080",
                "ea8080",
                "108080",
                "108080",
                "108080",
                "108080",
            ],
            "angles": 5,
            "audio": [
                {
                    "ix": 1,
                    "langcode": "en",
                    "language": "English",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x80",
                },
                {
                    "ix": 2,
                    "langcode": "no",
                    "language": "Norsk",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x81",
                },
                {
                    "ix": 3,
                    "langcode": "da",
                    "language": "Dansk",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x82",
                },
            ],
            "chapter": [{"ix": 1, "length": 27.04, "startcell": 1}],
            "cell": [{"ix": 1, "length": 27.04, "first_sector": 134658, "last_sector": 135725}],
            "subp": [{"ix": 1, "langcode": "xx", "language": "Unknown", "content": "Undefined", "streamid": "0x20"}],
        },
        {
            "ix": 16,
            "length": 27.04,
            "vts_id": "DVDVIDEO-VTS",
            "vts": 9,
            "ttn": 4,
            "fps": 25.0,
            "format": "PAL",
            "aspect": "4/3",
            "width": 720,
            "height": 576,
            "df": "?",
            "palette": [
                "286df0",
                "51f05a",
                "108080",
                "ea8080",
                "ea8080",
                "48d364",
                "b79227",
                "ea8080",
                "ea8080",
                "ea8080",
                "ea8080",
                "ea8080",
                "108080",
                "108080",
                "108080",
                "108080",
            ],
            "angles": 7,
            "audio": [
                {
                    "ix": 1,
                    "langcode": "en",
                    "language": "English",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x80",
                },
                {
                    "ix": 2,
                    "langcode": "no",
                    "language": "Norsk",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x81",
                },
                {
                    "ix": 3,
                    "langcode": "da",
                    "language": "Dansk",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x82",
                },
            ],
            "chapter": [{"ix": 1, "length": 27.04, "startcell": 1}],
            "cell": [{"ix": 1, "length": 27.04, "first_sector": 287079, "last_sector": 288146}],
            "subp": [{"ix": 1, "langcode": "xx", "language": "Unknown", "content": "Undefined", "streamid": "0x20"}],
        },
    ],
    "longest_track": 1,
}

y = {
    "device": "output/Blaafjelld1/VIDEO_TS",
    "title": "unknown",
    "vmg_id": "DVDVIDEO-VMG",
    "provider_id": "",
    "track": [
        {
            "ix": 1,
            "length": 1472.92,
            "vts_id": "DVDVIDEO-VTS",
            "vts": 1,
            "ttn": 1,
            "fps": 25.0,
            "format": "PAL",
            "aspect": "4/3",
            "width": 720,
            "height": 576,
            "df": "?",
            "palette": [
                "286df0",
                "51f05a",
                "108080",
                "ea8080",
                "902235",
                "6addca",
                "d29210",
                "5b4992",
                "7b8080",
                "d18080",
                "30b66d",
                "4f515b",
                "1c77b6",
                "61cfcf",
                "88b33a",
                "3caea4",
            ],
            "angles": 1,
            "audio": [
                {
                    "ix": 1,
                    "langcode": "en",
                    "language": "English",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x80",
                }
            ],
            "chapter": [{"ix": 1, "length": 479.12, "startcell": 1}, {"ix": 2, "length": 510.84, "startcell": 2}, {"ix": 3, "length": 482.96, "startcell": 3}],
            "cell": [
                {"ix": 1, "length": 479.12, "first_sector": 0, "last_sector": 125215},
                {"ix": 2, "length": 510.84, "first_sector": 125216, "last_sector": 258720},
                {"ix": 3, "length": 482.96, "first_sector": 258721, "last_sector": 384937},
            ],
            "subp": [],
        },
        {
            "ix": 2,
            "length": 1472.12,
            "vts_id": "DVDVIDEO-VTS",
            "vts": 1,
            "ttn": 2,
            "fps": 25.0,
            "format": "PAL",
            "aspect": "4/3",
            "width": 720,
            "height": 576,
            "df": "?",
            "palette": [
                "286df0",
                "51f05a",
                "108080",
                "ea8080",
                "902235",
                "6addca",
                "d29210",
                "5b4992",
                "7b8080",
                "d18080",
                "30b66d",
                "4f515b",
                "1c77b6",
                "61cfcf",
                "88b33a",
                "3caea4",
            ],
            "angles": 1,
            "audio": [
                {
                    "ix": 1,
                    "langcode": "en",
                    "language": "English",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x80",
                }
            ],
            "chapter": [{"ix": 1, "length": 489.36, "startcell": 1}, {"ix": 2, "length": 442.24, "startcell": 2}, {"ix": 3, "length": 540.52, "startcell": 3}],
            "cell": [
                {"ix": 1, "length": 489.36, "first_sector": 384938, "last_sector": 512818},
                {"ix": 2, "length": 442.24, "first_sector": 512819, "last_sector": 628400},
                {"ix": 3, "length": 540.52, "first_sector": 628401, "last_sector": 769666},
            ],
            "subp": [],
        },
        {
            "ix": 3,
            "length": 1471.88,
            "vts_id": "DVDVIDEO-VTS",
            "vts": 1,
            "ttn": 3,
            "fps": 25.0,
            "format": "PAL",
            "aspect": "4/3",
            "width": 720,
            "height": 576,
            "df": "?",
            "palette": [
                "286df0",
                "51f05a",
                "108080",
                "ea8080",
                "902235",
                "6addca",
                "d29210",
                "5b4992",
                "7b8080",
                "d18080",
                "30b66d",
                "4f515b",
                "1c77b6",
                "61cfcf",
                "88b33a",
                "3caea4",
            ],
            "angles": 1,
            "audio": [
                {
                    "ix": 1,
                    "langcode": "en",
                    "language": "English",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x80",
                }
            ],
            "chapter": [{"ix": 1, "length": 494.44, "startcell": 1}, {"ix": 2, "length": 470.68, "startcell": 2}, {"ix": 3, "length": 506.76, "startcell": 3}],
            "cell": [
                {"ix": 1, "length": 494.44, "first_sector": 769667, "last_sector": 898878},
                {"ix": 2, "length": 470.68, "first_sector": 898879, "last_sector": 1021863},
                {"ix": 3, "length": 506.76, "first_sector": 1021864, "last_sector": 1154300},
            ],
            "subp": [],
        },
        {
            "ix": 4,
            "length": 1472.68,
            "vts_id": "DVDVIDEO-VTS",
            "vts": 1,
            "ttn": 4,
            "fps": 25.0,
            "format": "PAL",
            "aspect": "4/3",
            "width": 720,
            "height": 576,
            "df": "?",
            "palette": [
                "286df0",
                "51f05a",
                "108080",
                "ea8080",
                "902235",
                "6addca",
                "d29210",
                "5b4992",
                "7b8080",
                "d18080",
                "30b66d",
                "4f515b",
                "1c77b6",
                "61cfcf",
                "88b33a",
                "3caea4",
            ],
            "angles": 1,
            "audio": [
                {
                    "ix": 1,
                    "langcode": "en",
                    "language": "English",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x80",
                }
            ],
            "chapter": [{"ix": 1, "length": 436.92, "startcell": 1}, {"ix": 2, "length": 368.88, "startcell": 2}, {"ix": 3, "length": 666.88, "startcell": 3}],
            "cell": [
                {"ix": 1, "length": 436.92, "first_sector": 1154301, "last_sector": 1268499},
                {"ix": 2, "length": 368.88, "first_sector": 1268500, "last_sector": 1364904},
                {"ix": 3, "length": 666.88, "first_sector": 1364905, "last_sector": 1539202},
            ],
            "subp": [],
        },
        {
            "ix": 5,
            "length": 1471.24,
            "vts_id": "DVDVIDEO-VTS",
            "vts": 1,
            "ttn": 5,
            "fps": 25.0,
            "format": "PAL",
            "aspect": "4/3",
            "width": 720,
            "height": 576,
            "df": "?",
            "palette": [
                "286df0",
                "51f05a",
                "108080",
                "ea8080",
                "902235",
                "6addca",
                "d29210",
                "5b4992",
                "7b8080",
                "d18080",
                "30b66d",
                "4f515b",
                "1c77b6",
                "61cfcf",
                "88b33a",
                "3caea4",
            ],
            "angles": 1,
            "audio": [
                {
                    "ix": 1,
                    "langcode": "en",
                    "language": "English",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x80",
                }
            ],
            "chapter": [{"ix": 1, "length": 614.64, "startcell": 1}, {"ix": 2, "length": 505.96, "startcell": 2}, {"ix": 3, "length": 350.64, "startcell": 3}],
            "cell": [
                {"ix": 1, "length": 614.64, "first_sector": 1539203, "last_sector": 1699824},
                {"ix": 2, "length": 505.96, "first_sector": 1699825, "last_sector": 1832038},
                {"ix": 3, "length": 350.64, "first_sector": 3779013, "last_sector": 3870660},
            ],
            "subp": [],
        },
        {
            "ix": 6,
            "length": 1472.92,
            "vts_id": "DVDVIDEO-VTS",
            "vts": 1,
            "ttn": 6,
            "fps": 25.0,
            "format": "PAL",
            "aspect": "4/3",
            "width": 720,
            "height": 576,
            "df": "?",
            "palette": [
                "286df0",
                "51f05a",
                "108080",
                "ea8080",
                "902235",
                "6addca",
                "d29210",
                "5b4992",
                "7b8080",
                "d18080",
                "30b66d",
                "4f515b",
                "1c77b6",
                "61cfcf",
                "88b33a",
                "3caea4",
            ],
            "angles": 1,
            "audio": [
                {
                    "ix": 1,
                    "langcode": "en",
                    "language": "English",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x80",
                }
            ],
            "chapter": [{"ix": 1, "length": 236.16, "startcell": 1}, {"ix": 2, "length": 702.92, "startcell": 2}, {"ix": 3, "length": 533.84, "startcell": 3}],
            "cell": [
                {"ix": 1, "length": 236.16, "first_sector": 1832039, "last_sector": 1893746},
                {"ix": 2, "length": 702.92, "first_sector": 1893747, "last_sector": 2077468},
                {"ix": 3, "length": 533.84, "first_sector": 2077469, "last_sector": 2216987},
            ],
            "subp": [],
        },
        {
            "ix": 7,
            "length": 1472.4,
            "vts_id": "DVDVIDEO-VTS",
            "vts": 1,
            "ttn": 7,
            "fps": 25.0,
            "format": "PAL",
            "aspect": "4/3",
            "width": 720,
            "height": 576,
            "df": "?",
            "palette": [
                "286df0",
                "51f05a",
                "108080",
                "ea8080",
                "902235",
                "6addca",
                "d29210",
                "5b4992",
                "7b8080",
                "d18080",
                "30b66d",
                "4f515b",
                "1c77b6",
                "61cfcf",
                "88b33a",
                "3caea4",
            ],
            "angles": 1,
            "audio": [
                {
                    "ix": 1,
                    "langcode": "en",
                    "language": "English",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x80",
                }
            ],
            "chapter": [{"ix": 1, "length": 544.0, "startcell": 1}, {"ix": 2, "length": 565.52, "startcell": 2}, {"ix": 3, "length": 362.88, "startcell": 3}],
            "cell": [
                {"ix": 1, "length": 544.0, "first_sector": 2216988, "last_sector": 2359152},
                {"ix": 2, "length": 565.52, "first_sector": 2359153, "last_sector": 2506948},
                {"ix": 3, "length": 362.88, "first_sector": 2506949, "last_sector": 2601785},
            ],
            "subp": [],
        },
        {
            "ix": 8,
            "length": 1472.8,
            "vts_id": "DVDVIDEO-VTS",
            "vts": 1,
            "ttn": 8,
            "fps": 25.0,
            "format": "PAL",
            "aspect": "4/3",
            "width": 720,
            "height": 576,
            "df": "?",
            "palette": [
                "286df0",
                "51f05a",
                "108080",
                "ea8080",
                "902235",
                "6addca",
                "d29210",
                "5b4992",
                "7b8080",
                "d18080",
                "30b66d",
                "4f515b",
                "1c77b6",
                "61cfcf",
                "88b33a",
                "3caea4",
            ],
            "angles": 1,
            "audio": [
                {
                    "ix": 1,
                    "langcode": "en",
                    "language": "English",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x80",
                }
            ],
            "chapter": [{"ix": 1, "length": 531.16, "startcell": 1}, {"ix": 2, "length": 493.48, "startcell": 2}, {"ix": 3, "length": 448.16, "startcell": 3}],
            "cell": [
                {"ix": 1, "length": 531.16, "first_sector": 2601786, "last_sector": 2740599},
                {"ix": 2, "length": 493.48, "first_sector": 2740600, "last_sector": 2869573},
                {"ix": 3, "length": 448.16, "first_sector": 2869574, "last_sector": 2986712},
            ],
            "subp": [],
        },
        {
            "ix": 9,
            "length": 1984.88,
            "vts_id": "DVDVIDEO-VTS",
            "vts": 1,
            "ttn": 9,
            "fps": 25.0,
            "format": "PAL",
            "aspect": "4/3",
            "width": 720,
            "height": 576,
            "df": "?",
            "palette": [
                "286df0",
                "51f05a",
                "108080",
                "ea8080",
                "902235",
                "6addca",
                "d29210",
                "5b4992",
                "7b8080",
                "d18080",
                "30b66d",
                "4f515b",
                "1c77b6",
                "61cfcf",
                "88b33a",
                "3caea4",
            ],
            "angles": 1,
            "audio": [
                {
                    "ix": 1,
                    "langcode": "en",
                    "language": "English",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x80",
                }
            ],
            "chapter": [{"ix": 1, "length": 1074.2, "startcell": 1}, {"ix": 2, "length": 910.68, "startcell": 2}],
            "cell": [
                {"ix": 1, "length": 1074.2, "first_sector": 3047753, "last_sector": 3394794},
                {"ix": 2, "length": 910.68, "first_sector": 3394795, "last_sector": 3689015},
            ],
            "subp": [],
        },
        {
            "ix": 10,
            "length": 52.0,
            "vts_id": "DVDVIDEO-VTS",
            "vts": 1,
            "ttn": 10,
            "fps": 25.0,
            "format": "PAL",
            "aspect": "4/3",
            "width": 720,
            "height": 576,
            "df": "?",
            "palette": [
                "286df0",
                "51f05a",
                "108080",
                "ea8080",
                "902235",
                "6addca",
                "d29210",
                "5b4992",
                "7b8080",
                "d18080",
                "30b66d",
                "4f515b",
                "1c77b6",
                "61cfcf",
                "88b33a",
                "3caea4",
            ],
            "angles": 1,
            "audio": [
                {
                    "ix": 1,
                    "langcode": "en",
                    "language": "English",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x80",
                }
            ],
            "chapter": [{"ix": 1, "length": 52.0, "startcell": 1}],
            "cell": [{"ix": 1, "length": 52.0, "first_sector": 3726149, "last_sector": 3752579}],
            "subp": [],
        },
        {
            "ix": 11,
            "length": 52.0,
            "vts_id": "DVDVIDEO-VTS",
            "vts": 1,
            "ttn": 11,
            "fps": 25.0,
            "format": "PAL",
            "aspect": "4/3",
            "width": 720,
            "height": 576,
            "df": "?",
            "palette": [
                "286df0",
                "51f05a",
                "108080",
                "ea8080",
                "902235",
                "6addca",
                "d29210",
                "5b4992",
                "7b8080",
                "d18080",
                "30b66d",
                "4f515b",
                "1c77b6",
                "61cfcf",
                "88b33a",
                "3caea4",
            ],
            "angles": 1,
            "audio": [
                {
                    "ix": 1,
                    "langcode": "en",
                    "language": "English",
                    "format": "ac3",
                    "frequency": 48000,
                    "quantization": "drc",
                    "channels": 2,
                    "ap_mode": 0,
                    "content": "Undefined",
                    "streamid": "0x80",
                }
            ],
            "chapter": [{"ix": 1, "length": 52.0, "startcell": 1}],
            "cell": [{"ix": 1, "length": 52.0, "first_sector": 3752580, "last_sector": 3779012}],
            "subp": [],
        },
    ],
    "longest_track": 9,
}

if __name__ == "__main__":
    x = lsdvd("output/Blaafjelld1/VIDEO_TS")
    print(x)
